[package]
name = "arkdiscordchat"
version = "1.1.1"
authors = ["Rens Rikkerink <contact@ikkerens.com>"]
edition = "2018"

[dependencies]
envmnt = "0.6"
rercon = "1.1"
serenity = "0.7"
regex = "1.2"
lazy_static = "1.3"