[package]
name = "ark_discord_chat"
version = "0.1.0"
authors = ["Rens Rikkerink <contact@ikkerens.com>"]
edition = "2018"

[dependencies]
envmnt = "0.6.0"
rercon = "0.1.1"
serenity = "0.6.3"
regex = "1.2.1"
lazy_static = "1.3.0"