name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Prepare cross compilation
        run: cargo install cross

      # Basic tests
      - name: Checkout git repository
        uses: actions/checkout@v1
      - name: Test code formatting
        run: cargo fmt --all -- --check
      - name: Test code correctness
        run: cargo clippy --all -- -D warnings

      # Prepare crate
      # Disabled because we depend on a crate that is not yet on crates.io
      #- name: Set crate version
      #  run: sed -i "s/^\(version = \).*/version = \"$(git describe --tags)\"/g" ./Cargo.toml
      #- name: Publish crate
      #  run: cargo login ${{ secrets.CRATES_IO_TOKEN }} && cargo publish --allow-dirty # Dirty because we modified Cargo.toml

      # Prepare github release
      - name: Build linux
        run: cargo build --release
      - name: Build windows
        run: cross build --release --target x86_64-pc-windows-gnu
      - name: Publish release assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/release/arkdiscordchat
            target/x86_64-pc-windows-gnu/release/arkdiscordchat.exe

      # Prepare docker release
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ikkerens/arkdiscordchat
          username: ikkerens
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.0.0
        env:
          DOCKERHUB_USERNAME: ikkerens
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: ikkerens/arkdiscordchat